### ISSUE TITLE
Breaks with Radium 0.18.2 (latest release)

### ISSUE THREAD

**Issue by adailey14** [negomi/react-burger-menu#138]
I can't pretend to understand why, but my latest npm install updated Radium to 0.18.2, which led to this error:

```
TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/var/app/current/node_modules/radium/lib/components/style.js:25:113)
    at /var/app/current/node_modules/radium/lib/components/style.js:28:3
    at Object.<anonymous> (/var/app/current/node_modules/radium/lib/components/style.js:92:2)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/app/current/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Maybe someone smarter than me can make sense of that.

**Comment by adailey14** [comment]
Someone pointed out to me that this is because I am using a React version before 15.3. I will close this.
