### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by msimonc** [negomi/react-burger-menu#31]
I'm seeing the tests have a config issue:

Error: Cannot find module 'babel/register'

Thx!

**Comment by negomi** [comment]
I think this is happening because one of the dependencies is still looking for the old Babel package, which I removed recently as it's deprecated. You might need to `rm -rf node_modules && npm install`

**Comment by msimonc** [comment]
You should be able to reproduce this as I installed just yesterday, Thx!

**Comment by negomi** [comment]
Just tried with a fresh install and I'm still not getting that error. Could you post the full stack trace? Thanks.

**Comment by msimonc** [comment]
No wuriz:
$ npm test

> react-burger-menu@1.4.7 test /ProjectSamples/REACT/react-burger-menu
> mocha --reporter dot

module.js:338
    throw err;
          ^
Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /ProjectSamples/REACT/react-burger-menu/node_modules/mocha/bin/_mocha:296:3
    at Array.forEach (native)
    at Object.<anonymous> (/ProjectSamples/REACT/react-burger-menu/node_modules/mocha/bin/_mocha:290:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.

**Comment by negomi** [comment]
Ah right. I think you might have a cached version of an outdated package. Have your tried clearing your cache with `npm cache clean`?

**Comment by msimonc** [comment]
Still no change.  
$ mocha --version
2.2.5 
?

**Comment by negomi** [comment]
Digging into this a bit more, it looks like it's to do with having upgraded to Babel 6. I'm working on it :)

**Comment by negomi** [comment]
Ok, I think this should now be fixed for you. I just released v1.4.8 which includes some changes around running the tests, to work better with Babel 6.

**Comment by msimonc** [comment]
I've done:
npm -g update
npm install
npm cache clean
npm test

I get:
> react-burger-menu@1.4.8 test /ProjectSamples/REACT/react-burger-menu
> gulp test --reporter dot

/ProjectSamples/REACT/react-burger-menu/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/ProjectSamples/REACT/react-burger-menu/node_modules/babel-register/lib/node.js:138:7)

Thanks, Mark

**Comment by msimonc** [comment]
Fixed.

**Comment by negomi** [comment]
Great, glad to hear it!
