### ISSUE TITLE
[Feature Request, maybe] Logo image on top of the menu

### ISSUE THREAD

**Issue by Yaroslav-F** [negomi/react-burger-menu#335]
Hello,

I was trying to add logo on top of the menu. A bit like in Push-Rotate example, but with `Sidebar` being image instead of the icon + span.
So I'm trying to do:
```
import React from 'react'
import { slide as Menu } from 'react-burger-menu'

import LogoMobile from '../assets/images/mobile-menu-logo.jpg'

class MobileMenu extends React.Component {
  render() {
    return (
      <Menu isOpen={this.props.isOpen}>
        <LogoMobile />
        <a href='#'>Item 1</a>
        <a href='#'>Item 2</a>
        <a href='#'>Item 3</a>
      </Menu>
    )
  }
}

export default MobileMenu;
```
The error I'm getting is:
```
Unhandled Rejection (InvalidCharacterError): Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/mobile-menu-logo.f6d9b88d.jpg') is not a valid name.
```

I take it that's because Menu is creating items dynamically. Is there any way around this, except uploading the image somewhere and using `<img />` tag?

Thanks in advance
Y

**Comment by negomi** [comment]
@Yaroslav-F you could wrap `<LogoMobile />` in a div or span?

**Comment by Yaroslav-F** [comment]
@negomi Sorry it took me a while to respond, just came back to this project.
So I did as you asked:
```
import React                          from 'react'
import { slide as Menu }              from 'react-burger-menu'
import LogoMobile from '../assets/images/mobile-nav-logo.jpg'

class MobileMenu extends React.Component {
  render() {
    return (
      <Menu isOpen={this.props.isOpen} onStateChange={state => this.props.stateChangeHandler(state.isOpen)}>
        <div className='text-center p-4'>
          <LogoMobile />
        </div>
        <div className='btn-group-vertical'>
          <a href='#">a</a>
          <a href='#' className="btn btn-outline-light text-left">b</a>
          <a href='#' className="btn btn-outline-light text-left">c</a>
        </div>
      </Menu>
    )
  }
}

export default MobileMenu;
```
Getting pretty much the same error though:
```
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/mobile-nav-logo.f6d9b88d.jpg') is not a valid name.
    at createElement (http://localhost:3000/static/js/0.chunk.js:135324:38)
    at createInstance (http://localhost:3000/static/js/0.chunk.js:136520:24)

index.js:1375 The above error occurred in the </static/media/mobile-nav-logo.f6d9b88d.jpg> component:
    in /static/media/mobile-nav-logo.f6d9b88d.jpg (at mobile-menu.js:13)
    in div (at mobile-menu.js:12)
    in nav (created by Menu)
    in div (created by Menu)
    in div (created by Menu)
    in div (created by Menu)
    in Menu (at mobile-menu.js:11)
    in MobileMenu (at navbar.js:37)
```

**Comment by negomi** [comment]
Oh I see, sorry, I didn't look at how you were importing it before.

I assume you're importing it with the Webpack file-loader [as described here](https://webpack.js.org/guides/asset-management/#loading-images), in which case it won't import a component, but a URL:

> Now, when you import MyImage from './my-image.png', that image will be processed and added to your output directory and the MyImage variable will contain the final url of that image after processing.

So I think your code needs to do this:
```js
import React from 'react'
import { slide as Menu } from 'react-burger-menu'

import LogoMobile from '../assets/images/mobile-menu-logo.jpg'

class MobileMenu extends React.Component {
  render() {
    return (
      <Menu isOpen={this.props.isOpen}>
        <img src={LogoMobile} />
        <a href='#'>Item 1</a>
        <a href='#'>Item 2</a>
        <a href='#'>Item 3</a>
      </Menu>
    )
  }
}

export default MobileMenu;
```

**Comment by Yaroslav-F** [comment]
Yep, that was it. Thank you very much! :)
